# Generated by Django 2.0.7 on 2018-10-14 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crcapp', '0007_auto_20180904_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='Order_CreateDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='orders',
            name='Order_ReturnDate',
            field=models.DateField(),
        ),
    ]
